name: Build Simple Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PKG globally
        run: |
          npm install -g pkg

      - name: Build with PKG
        run: |
          pkg . --target node18-win-x64 --output dist/main.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rfid-converter-exe
          path: dist/main.exe
